# Generated by Django 2.0.6 on 2018-07-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopStaticInfo',
            fields=[
                ('number', models.IntegerField()),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Stop_Static_Info',
                'managed': False,
            },
        ),
    ]
