# Generated by Django 2.0.6 on 2018-07-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DublinBusTest', '0002_line9_lineone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buslineinformation',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('location_text', models.TextField(blank=True, db_column='LOCATION_TEXT', null=True)),
                ('address', models.TextField(blank=True, db_column='ADDRESS', null=True)),
                ('status', models.TextField(blank=True, db_column='STATUS', null=True)),
                ('name', models.TextField(db_column='NAME', primary_key=True)),
                ('route_direction', models.TextField(db_column='ROUTE_DIRECTION', primary_key=True)),
                ('sequence', models.FloatField(blank=True, db_column='SEQUENCE', null=True)),
                ('is_stage_point', models.TextField(blank=True, db_column='IS_STAGE_POINT', null=True)),
                ('stage_number', models.TextField(blank=True, db_column='STAGE_NUMBER', null=True)),
                ('rtpi_destination', models.TextField(blank=True, db_column='RTPI_DESTINATION', null=True)),
                ('rtpi_orgin', models.TextField(blank=True, db_column='RTPI_ORGIN', null=True)),
                ('rtpi_via', models.TextField(blank=True, db_column='RTPI_VIA', null=True)),
                ('sequence_number', models.IntegerField(blank=True, db_column='SEQUENCE_NUMBER', null=True)),
            ],
            options={
                'db_table': 'BusLineInformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line1',
            fields=[
                ('displaystopid', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line102',
            fields=[
                ('displaystopid', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '102',
                'managed': False,
            },
        ),
    ]
