# Generated by Django 2.0.6 on 2018-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DublinBusTest', '0003_buslineinformation_line1_line102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busrouteinfo',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('location_text', models.TextField(blank=True, db_column='LOCATION_TEXT', null=True)),
                ('address', models.TextField(blank=True, db_column='ADDRESS', null=True)),
                ('status', models.TextField(blank=True, db_column='STATUS', null=True)),
                ('name', models.TextField(db_column='NAME', primary_key=True)),
                ('route_direction', models.TextField(db_column='ROUTE_DIRECTION', primary_key=True)),
                ('is_stage_point', models.TextField(blank=True, db_column='IS_STAGE_POINT', null=True)),
                ('stage_number', models.FloatField(blank=True, db_column='STAGE_NUMBER', null=True)),
                ('rtpi_destination', models.TextField(blank=True, db_column='RTPI_DESTINATION', null=True)),
                ('rtpi_orgin', models.TextField(blank=True, db_column='RTPI_ORGIN', null=True)),
                ('rtpi_via', models.TextField(blank=True, db_column='RTPI_VIA', null=True)),
                ('sequence_number', models.BigIntegerField(blank=True, db_column='SEQUENCE_NUMBER', null=True)),
            ],
            options={
                'db_table': 'BusRouteInfo',
                'managed': False,
            },
        ),
    ]
