# Generated by Django 2.0.6 on 2018-07-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DublinBusTest', '0004_busrouteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weatherforecast',
            fields=[
                ('dt_txt', models.TextField(primary_key=True, serialize=False)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('main', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WeatherForecast',
                'managed': False,
            },
        ),
    ]
