# Generated by Django 2.0.6 on 2018-08-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DublinBusTest', '0005_busrouteinfojoined_weatherforecast'),
        ('DublinBusTest', '0006_busrouteinfojoined'),
    ]

    operations = [
    ]
